// Date: 9/27/2014 10:13:34 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.beanbot.beancraft.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelBioInfuser extends ModelBase
{
  //fields
    ModelRenderer PowerReceiver;
    ModelRenderer InfusionPillar1;
    ModelRenderer InfusionPillar2;
    ModelRenderer BioMatrixCore;
    ModelRenderer BioMatrixNipple1;
    ModelRenderer BioMatrixNipple2;
    ModelRenderer BioMatrixNipple3;
    ModelRenderer BioMatrixNipple4;
    ModelRenderer BioMatrixNipple5;
    ModelRenderer BioMatrixNipple6;
    ModelRenderer BioMatrixNipple7;
    ModelRenderer Pipe1;
    ModelRenderer Pipe2;
    ModelRenderer Shape1;
  
  public ModelBioInfuser()
  {
    textureWidth = 64;
    textureHeight = 32;
    
      PowerReceiver = new ModelRenderer(this, 0, 0);
      PowerReceiver.addBox(2F, 16F, -3F, 6, 8, 6);
      PowerReceiver.setRotationPoint(0F, 0F, 0F);
      PowerReceiver.setTextureSize(64, 32);
      PowerReceiver.mirror = true;
      setRotation(PowerReceiver, 0F, 0F, 0F);
      InfusionPillar1 = new ModelRenderer(this, 25, 0);
      InfusionPillar1.addBox(-8F, 12F, -8F, 6, 12, 6);
      InfusionPillar1.setRotationPoint(0F, 0F, 0F);
      InfusionPillar1.setTextureSize(64, 32);
      InfusionPillar1.mirror = true;
      setRotation(InfusionPillar1, 0F, 0F, 0F);
      InfusionPillar2 = new ModelRenderer(this, 25, 0);
      InfusionPillar2.addBox(-8F, 12F, 2F, 6, 12, 6);
      InfusionPillar2.setRotationPoint(0F, 0F, 0F);
      InfusionPillar2.setTextureSize(64, 32);
      InfusionPillar2.mirror = true;
      setRotation(InfusionPillar2, 0F, 0F, 0F);
      BioMatrixCore = new ModelRenderer(this, 0, 24);
      BioMatrixCore.addBox(0F, 0F, 0F, 4, 2, 4);
      BioMatrixCore.setRotationPoint(4F, 14F, -2F);
      BioMatrixCore.setTextureSize(64, 32);
      BioMatrixCore.mirror = true;
      setRotation(BioMatrixCore, 0F, 0F, 0F);
      BioMatrixNipple1 = new ModelRenderer(this, 5, 28);
      BioMatrixNipple1.addBox(8F, 15F, -1F, 1, 2, 2);
      BioMatrixNipple1.setRotationPoint(0F, 0F, 0F);
      BioMatrixNipple1.setTextureSize(64, 32);
      BioMatrixNipple1.mirror = true;
      setRotation(BioMatrixNipple1, 0F, 0F, 0F);
      BioMatrixNipple2 = new ModelRenderer(this, 5, 28);
      BioMatrixNipple2.addBox(5F, 15F, 2F, 2, 1, 1);
      BioMatrixNipple2.setRotationPoint(0F, 0F, 0F);
      BioMatrixNipple2.setTextureSize(64, 32);
      BioMatrixNipple2.mirror = true;
      setRotation(BioMatrixNipple2, 0F, 0F, 0F);
      BioMatrixNipple3 = new ModelRenderer(this, 5, 28);
      BioMatrixNipple3.addBox(5F, 15F, -3F, 2, 1, 1);
      BioMatrixNipple3.setRotationPoint(0F, 0F, 0F);
      BioMatrixNipple3.setTextureSize(64, 32);
      BioMatrixNipple3.mirror = true;
      setRotation(BioMatrixNipple3, 0F, 0F, 0F);
      BioMatrixNipple4 = new ModelRenderer(this, 5, 28);
      BioMatrixNipple4.addBox(3F, 15F, -1F, 1, 1, 2);
      BioMatrixNipple4.setRotationPoint(0F, 0F, 0F);
      BioMatrixNipple4.setTextureSize(64, 32);
      BioMatrixNipple4.mirror = true;
      setRotation(BioMatrixNipple4, 0F, 0F, 0F);
      BioMatrixNipple5 = new ModelRenderer(this, 5, 28);
      BioMatrixNipple5.addBox(5F, 13F, -1F, 2, 1, 2);
      BioMatrixNipple5.setRotationPoint(0F, 0F, 0F);
      BioMatrixNipple5.setTextureSize(64, 32);
      BioMatrixNipple5.mirror = true;
      setRotation(BioMatrixNipple5, 0F, 0F, 0F);
      BioMatrixNipple6 = new ModelRenderer(this, 5, 28);
      BioMatrixNipple6.addBox(-6F, 11F, -6F, 2, 1, 2);
      BioMatrixNipple6.setRotationPoint(0F, 0F, 0F);
      BioMatrixNipple6.setTextureSize(64, 32);
      BioMatrixNipple6.mirror = true;
      setRotation(BioMatrixNipple6, 0F, 0F, 0F);
      BioMatrixNipple7 = new ModelRenderer(this, 5, 28);
      BioMatrixNipple7.addBox(-6F, 11F, 4F, 2, 1, 2);
      BioMatrixNipple7.setRotationPoint(0F, 0F, 0F);
      BioMatrixNipple7.setTextureSize(64, 32);
      BioMatrixNipple7.mirror = true;
      setRotation(BioMatrixNipple7, 0F, 0F, 0F);
      Pipe1 = new ModelRenderer(this, 25, 19);
      Pipe1.addBox(5F, 9F, -1F, 2, 4, 2);
      Pipe1.setRotationPoint(0F, 0F, 0F);
      Pipe1.setTextureSize(64, 32);
      Pipe1.mirror = true;
      setRotation(Pipe1, 0F, 0F, 0F);
      Pipe2 = new ModelRenderer(this, 20, 26);
      Pipe2.addBox(-6F, 9F, -1F, 11, 2, 2);
      Pipe2.setRotationPoint(0F, 0F, 0F);
      Pipe2.setTextureSize(64, 32);
      Pipe2.mirror = true;
      setRotation(Pipe2, 0F, 0F, 0F);
      Shape1 = new ModelRenderer(this, 36, 18);
      Shape1.addBox(-6F, 9F, -6F, 2, 2, 12);
      Shape1.setRotationPoint(0F, 0F, 0F);
      Shape1.setTextureSize(64, 32);
      Shape1.mirror = true;
      setRotation(Shape1, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    PowerReceiver.render(f5);
    InfusionPillar1.render(f5);
    InfusionPillar2.render(f5);
    BioMatrixCore.render(f5);
    BioMatrixNipple1.render(f5);
    BioMatrixNipple2.render(f5);
    BioMatrixNipple3.render(f5);
    BioMatrixNipple4.render(f5);
    BioMatrixNipple5.render(f5);
    BioMatrixNipple6.render(f5);
    BioMatrixNipple7.render(f5);
    Pipe1.render(f5);
    Pipe2.render(f5);
    Shape1.render(f5);
  }

  public void renderModel(float f)
  {
      PowerReceiver.render(f);
      InfusionPillar1.render(f);
      InfusionPillar2.render(f);
      BioMatrixCore.render(f);
      BioMatrixNipple1.render(f);
      BioMatrixNipple2.render(f);
      BioMatrixNipple3.render(f);
      BioMatrixNipple4.render(f);
      BioMatrixNipple5.render(f);
      BioMatrixNipple6.render(f);
      BioMatrixNipple7.render(f);
      Pipe1.render(f);
      Pipe2.render(f);
      Shape1.render(f);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
