// Date: 9/13/2014 2:12:14 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.beanbot.beancraft.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelBioCrystal extends ModelBase
{
  //fields
    public ModelRenderer Main_Cube;
    public ModelRenderer Augments_1;
    public ModelRenderer Augments_2;
    public ModelRenderer Augments_3;
  
  public ModelBioCrystal()
  {
    textureWidth = 64;
    textureHeight = 32;
    
      Main_Cube = new ModelRenderer(this, 0, 0);
      Main_Cube.addBox(-2F, -1F, -2F, 4, 4, 4);
      Main_Cube.setRotationPoint(0F, 0F, 0F);
      Main_Cube.setTextureSize(64, 32);
      Main_Cube.mirror = true;
      setRotation(Main_Cube, 0F, 0F, 0F);
      Augments_1 = new ModelRenderer(this, 18, 0);
      Augments_1.addBox(-3F, 0F, -1F, 6, 2, 2);
      Augments_1.setRotationPoint(0F, 0F, 0F);
      Augments_1.setTextureSize(64, 32);
      Augments_1.mirror = true;
      setRotation(Augments_1, 0F, 0F, 0F);
      Augments_2 = new ModelRenderer(this, 16, 12);
      Augments_2.addBox(-1F, 0F, -3F, 2, 2, 6);
      Augments_2.setRotationPoint(0F, 0F, 0F);
      Augments_2.setTextureSize(64, 32);
      Augments_2.mirror = true;
      setRotation(Augments_2, 0F, 0F, 0F);
      Augments_3 = new ModelRenderer(this, 0, 12);
      Augments_3.addBox(-1F, -2F, -1F, 2, 6, 2);
      Augments_3.setRotationPoint(0F, 0F, 0F);
      Augments_3.setTextureSize(64, 32);
      Augments_3.mirror = true;
      setRotation(Augments_3, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    Main_Cube.render(f5);
    Augments_1.render(f5);
    Augments_2.render(f5);
    Augments_3.render(f5);
  }

  public void renderModel(float f)
  {
      Main_Cube.render(f);
      Augments_1.render(f);
      Augments_2.render(f);
      Augments_3.render(f);
  }

  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
