// Date: 9/13/2014 8:53:24 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.beanbot.beancraft.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelBioGenerator extends ModelBase
{
  //fields
    ModelRenderer BioMatrix;
    ModelRenderer Holder1;
    ModelRenderer Holder2;
    ModelRenderer Base;
    ModelRenderer Leg1;
    ModelRenderer Leg2;
    ModelRenderer Leg3;
    ModelRenderer Leg4;
    ModelRenderer Holder3;
    ModelRenderer Holder4;
  
  public ModelBioGenerator()
  {
    textureWidth = 64;
    textureHeight = 32;
    
      BioMatrix = new ModelRenderer(this, 0, 0);
      BioMatrix.addBox(-1F, 13F, -1F, 2, 2, 2);
      BioMatrix.setRotationPoint(0F, 0F, 0F);
      BioMatrix.setTextureSize(64, 32);
      BioMatrix.mirror = true;
      setRotation(BioMatrix, 0F, 0F, 0F);
      //Holder1.mirror = true;
      Holder1 = new ModelRenderer(this, 32, 4);
      Holder1.addBox(-22F, 9F, -0.5F, 11, 1, 1);
      Holder1.setRotationPoint(0F, 0F, 0F);
      Holder1.setTextureSize(64, 32);
      Holder1.mirror = true;
      setRotation(Holder1, 0F, 0.7853982F, -0.7853982F);
      Holder1.mirror = false;
      Holder2 = new ModelRenderer(this, 32, 4);
      Holder2.addBox(11F, 9F, -0.5F, 11, 1, 1);
      Holder2.setRotationPoint(0F, 0F, 0F);
      Holder2.setTextureSize(64, 32);
      Holder2.mirror = true;
      setRotation(Holder2, 0F, 0.7853982F, 0.7853982F);
      Base = new ModelRenderer(this, 0, 15);
      Base.addBox(-7F, 20F, -7F, 14, 3, 14);
      Base.setRotationPoint(0F, 0F, 0F);
      Base.setTextureSize(64, 32);
      Base.mirror = true;
      setRotation(Base, 0F, 0F, 0F);
      Leg1 = new ModelRenderer(this, 14, 0);
      Leg1.addBox(6F, 21F, 6F, 2, 3, 2);
      Leg1.setRotationPoint(0F, 0F, 0F);
      Leg1.setTextureSize(64, 32);
      Leg1.mirror = true;
      setRotation(Leg1, 0F, 0F, 0F);
      Leg2 = new ModelRenderer(this, 14, 0);
      Leg2.addBox(-8F, 21F, 6F, 2, 3, 2);
      Leg2.setRotationPoint(0F, 0F, 0F);
      Leg2.setTextureSize(64, 32);
      Leg2.mirror = true;
      setRotation(Leg2, 0F, 0F, 0F);
      Leg3 = new ModelRenderer(this, 14, 0);
      Leg3.addBox(6F, 21F, -8F, 2, 3, 2);
      Leg3.setRotationPoint(0F, 0F, 0F);
      Leg3.setTextureSize(64, 32);
      Leg3.mirror = true;
      setRotation(Leg3, 0F, 0F, 0F);
      Leg4 = new ModelRenderer(this, 14, 0);
      Leg4.addBox(-8F, 21F, -8F, 2, 3, 2);
      Leg4.setRotationPoint(0F, 0F, 0F);
      Leg4.setTextureSize(64, 32);
      Leg4.mirror = true;
      setRotation(Leg4, 0F, 0F, 0F);
      Holder3 = new ModelRenderer(this, 32, 4);
      Holder3.addBox(11F, 9F, -0.5F, 11, 1, 1);
      Holder3.setRotationPoint(0F, 0F, 0F);
      Holder3.setTextureSize(64, 32);
      Holder3.mirror = true;
      setRotation(Holder3, 0F, -0.7853982F, 0.7853982F);
      Holder4 = new ModelRenderer(this, 32, 4);
      Holder4.addBox(11F, 9F, -0.5F, 11, 1, 1);
      Holder4.setRotationPoint(0F, 0F, 0F);
      Holder4.setTextureSize(64, 32);
      Holder4.mirror = true;
      setRotation(Holder4, 0F, 2.356194F, 0.7853982F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    BioMatrix.render(f5);
    Holder1.render(f5);
    Holder2.render(f5);
    Base.render(f5);
    Leg1.render(f5);
    Leg2.render(f5);
    Leg3.render(f5);
    Leg4.render(f5);
    Holder3.render(f5);
    Holder4.render(f5);
  }

  public void renderModel(float f)
  {
      BioMatrix.render(f);
      Holder1.render(f);
      Holder2.render(f);
      Base.render(f);
      Leg1.render(f);
      Leg2.render(f);
      Leg3.render(f);
      Leg4.render(f);
      Holder3.render(f);
      Holder4.render(f);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
